<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class Unit_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    public function get_unit_duplicate($params)
    {
        $this->db->where('untName',$params['untName']);
        $query=$this->db->get('units');
        $c=$query->num_rows(); 
        if($c>0){
            return true;
        }
        else{
            return false; 
        }
    }

    public function get_update_unit_duplicate($id, $params)
    {
        $this->db->where('untName',$params['untName']);
        $this->db->where_not_in('untId', $id);
        $query=$this->db->get('units');
        $c=$query->num_rows(); 
        if($c>0){
            return true;
        }
        else{
            return false; 
        }
    }

    public function add_unit($params) {
        if($this->db->insert('units', $params)) {
            $insert_id = $this->db->insert_id();
            $data['untCode'] = 'LNUNIT00' . $insert_id;
            $this->db->where('untId', $insert_id);
            $this->db->update('units', $data);
            return true;
        } else {
            return false;
        }
    }


    public function get_all_units()
    {
        $this->db->select('*');
        $this->db->from('units');
        $query=$this->db->get();
        return $query->result_array();
    }

    public function get_all_user_units($id)
    {
        $this->db->select('*');
        $this->db->from('user_units');
        $this->db->join('units', 'units.untId = user_units.usruUnitId');
        $this->db->where('user_units.usruUserId',$id);
        $query=$this->db->get();
        return $query->result_array();
    }


    public function update_status($id, $params)
    {
        $this->db->where('untId',$id);
        $this->db->update('units',$params);

        if($this->db->affected_rows() == '1'){
            return true;
        }else{
            return false;
        }
    }

    public function get_unit_data($params)
    {
        return $this->db->get_where('units',$params)->row_array();
    }


    public function update_unit($id, $params)
    {
        $this->db->where('untId',$id);
        $this->db->update('units',$params);
    }

    

}
