<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }


    public function get_meeting_reports_by_date($params, $parent_path)
    {
        $this->db->select('*');
        $this->db->from('meetings');
        $this->db->join('customers', 'customers.cusId = meetings.mtnCustomerId');
        $this->db->join('users', 'users.usrId = meetings.mtnUserId');
        $this->db->where('meetings.mtnUserId',$params['userId']);

        if($params['customerTypeId']!=0){
            $this->db->where('customers.cusCustomerTypeId',$params['customerTypeId']);
        }
        if($params['industryTypeId']!=0){
            $this->db->where('customers.cusIndustryTypeId',$params['industryTypeId']);
        }
        if($params['companyId']!=0){
            $this->db->where('customers.cusCompanyName',$params['companyName']);
        }
        if($params['dateTypeValue']=="today"){

            $today = date('Y-m-d');
            $this->db->where('meetings.mtnDate >=',$today);
            $this->db->where('meetings.mtnDate <=',$today);

        }else if($params['dateTypeValue']=="tomorrow"){

            $tomorrow = date('Y-m-d', strtotime('+1 day'));
            $this->db->where('meetings.mtnDate >=',$tomorrow);
            $this->db->where('meetings.mtnDate <=',$tomorrow);

        }else if($params['dateTypeValue']=="coming7days"){

            $today = date('Y-m-d');
            $coming_seven_days = date('Y-m-d', strtotime('+7 days'));
            $this->db->where('meetings.mtnDate >=',$today);
            $this->db->where('meetings.mtnDate <=',$coming_seven_days);

        }else if($params['dateTypeValue']=="last7days"){

            $today = date('Y-m-d');
            $seven_day = date('Y-m-d', strtotime('-7 days'));
            $this->db->where('meetings.mtnDate >=',$seven_day);
            $this->db->where('meetings.mtnDate <=',$today);

        }else if($params['dateTypeValue']=="last30days"){

            $today = date('Y-m-d');
            $thirty_day = date('Y-m-d', strtotime('-30 days'));
            $this->db->where('meetings.mtnDate >=',$thirty_day);
            $this->db->where('meetings.mtnDate <=',$today);

        }else if($params['dateTypeValue']=="daterange"){

            $this->db->where('meetings.mtnDate >=',$params['fromDate']);
            $this->db->where('meetings.mtnDate <=',$params['toDate']);

        }

        $query=$this->db->get();
        return $query->result_array();
    }

    public function get_all_customer_types()
    {
        return $this->db->get('customer_types')->result_array();
    }

    public function get_all_customer_types_report()
    {
        $this->db->select('*');
        $this->db->from('customers');
        $this->db->join('customer_types', 'customer_types.custId = customers.cusCustomerTypeId');
        $this->db->group_by('customers.cusCustomerTypeId');
        $query=$this->db->get();
        return $query->result_array();
    }

    public function get_all_industry_types()
    {
        return $this->db->get('industry_types')->result_array();
    }

    public function get_all_industry_types_report()
    {
        $this->db->select('*');
        $this->db->from('customers');
        $this->db->join('industry_types', 'industry_types.indtId = customers.cusIndustryTypeId');
        $this->db->group_by('customers.cusIndustryTypeId');
        $query=$this->db->get();
        return $query->result_array();
    }

    public function get_all_companies()
    {
        return $this->db->get('companies')->result_array();
    }

    public function get_all_companies_report()
    {
        $this->db->select('*');
        $this->db->from('customers');
        $this->db->join('companies', 'companies.cmpName = customers.cusCompanyName');
        $this->db->group_by('customers.cusCompanyName');
        $query=$this->db->get();
        return $query->result_array();
    }
   

}
